server:
  port: 8761

notlocalhost: 192.168.1.199

eureka:
  instance:
    hostname: ${notlocalhost:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
